name: different

on: [push]

jobs:  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Python - Set Up
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: Python - Version
      run: |
        python --version
